import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import TaskCard from "@/components/taskCard";
import TaskForm from "@/components/taskForm";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [task, setTask] = useState<any>();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mx-auto">
        <div>
          <h1 className="text-2xl"> TO DO APP </h1>
          <TaskForm setTask={setTask} />
          <li>
            <ul>todo-1</ul>
            <ul>todo-2</ul>
            <ul>todo-3</ul>
          </li>
        </div>
      </main>
    </>
  );
}
