import Head from "next/head";
import { Inter } from "next/font/google";
import TaskCard from "@/components/taskCard";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [task, setTask] = useState<any>([]);
  const [newTask, setNewTask] = useState("");

  const addTask = () => {
    if (task) {
      let num = task.length + 1;
      let newEntry = { id: num, title: newTask };
      setTask([...task, newEntry]);
      console.log(task);
      setNewTask("");
    }
  };

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    e.preventDefault();
    setNewTask(e.target.value);
  };
  return (
    <>
      <Head>
        <title>Todo App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mx-auto w-full h-screen">
        <div className="w-full flex justify-center">
          <div>
            <div className="w-96 h-fit mx-auto">
              <h1 className="text-2xl text-center my-10"> TO DO APP </h1>
              <div className=" flex flex-col space-y-6">
                <input
                  type="text"
                  value={newTask}
                  maxLength={80}
                  placeholder="Enter tasks here..."
                  onChange={handleInputChange}
                  className="flex-1 w-full text-lg px-3 py-2 rounded-lg"
                />
                <button
                  onClick={addTask}
                  className="w-28 mx-auto h-10 border-2 rounded-xl"
                >
                  Add task
                </button>
              </div>
            </div>
            <div className="mt-12">
              {task.length == 0 ? (
                <div className="text-gray-300 text-center">
                  <h1>It seems empty here. Try adding new Tasks</h1>
                </div>
              ) : (
                <section className="flex flex-col space-y-5">
                  {task.map((task: string, idx: number) => (
                    <TaskCard task={task} idx={idx} />
                  ))}
                </section>
              )}
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
